// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx_OJQ1M8SM909WV_YEDaEDT_NIyuePNM',
    appId: '1:744938288137:web:477e4b67d7f60c846eb4d8',
    messagingSenderId: '744938288137',
    projectId: 'recipeflow-7212a',
    authDomain: 'recipeflow-7212a.firebaseapp.com',
    storageBucket: 'recipeflow-7212a.firebasestorage.app',
    measurementId: 'G-MMNGRS9Z0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkEXxjIl93jEV5D5OBDh8rmZnH2Yj_jN8',
    appId: '1:744938288137:android:b63f0385138791cf6eb4d8',
    messagingSenderId: '744938288137',
    projectId: 'recipeflow-7212a',
    storageBucket: 'recipeflow-7212a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6O15CQBzfbacWoVKQGazKgFO7rDQb4kU',
    appId: '1:744938288137:ios:73d82e79fffaa3306eb4d8',
    messagingSenderId: '744938288137',
    projectId: 'recipeflow-7212a',
    storageBucket: 'recipeflow-7212a.firebasestorage.app',
    iosClientId: '744938288137-ou1p6oon38lpppngk0gm3smg9sp4blmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
