// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQIj_zg349hkceXJuxDa_I03cQXZIiXGI',
    appId: '1:1072525701664:web:9626f22ea80835d1f34245',
    messagingSenderId: '1072525701664',
    projectId: 'recipeflow-dev',
    authDomain: 'recipeflow-dev.firebaseapp.com',
    storageBucket: 'recipeflow-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhBEjv4N2KqCOG81hOisNtLlWaDXX-mkA',
    appId: '1:1072525701664:android:2c001a233a056f49f34245',
    messagingSenderId: '1072525701664',
    projectId: 'recipeflow-dev',
    storageBucket: 'recipeflow-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCePDqCSNslkcC7BKtFF9CTDFbiZl1pZmk',
    appId: '1:1072525701664:ios:518aedf057666c6df34245',
    messagingSenderId: '1072525701664',
    projectId: 'recipeflow-dev',
    storageBucket: 'recipeflow-dev.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );
}
